import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import {
  Form,
  Link,
  useFetcher,
  useLoaderData,
  useNavigation,
} from "react-router";
import { boundary } from "@shopify/shopify-app-react-router/server";
import { authenticate } from "../shopify.server";
import { getProductCatalog } from "../product-catalog-cache.server";
import { runWithAnalyticsCache } from "../analytics-cache.server";
import { runShopifyQL } from "../shopifyql.server";
import { generateNewArrivalReport } from "../new-arrival-engine.server";
import styles from "../styles/new-arrivals.css?url";

/* Loader data and local table component props are runtime-validated by React Router. */
/* eslint-disable react/prop-types */

const PAGE_SIZE = 50;
const categoryLoadQueue = [];
let activeCategoryLoads = 0;
function runCategoryQueue() {
  while (activeCategoryLoads < 2 && categoryLoadQueue.length) {
    const item = categoryLoadQueue.shift();
    if (item.cancelled) continue;
    activeCategoryLoads += 1;
    item.start(() => {
      activeCategoryLoads = Math.max(0, activeCategoryLoads - 1);
      runCategoryQueue();
    });
  }
}
function enqueueCategoryLoad(start, priority = false) {
  const item = { start, cancelled: false };
  if (priority) categoryLoadQueue.unshift(item);
  else categoryLoadQueue.push(item);
  runCategoryQueue();
  return () => {
    item.cancelled = true;
  };
}
const MATRIX_METRICS = [
  [
    "naSkus",
    "NA SKUs",
    "number",
    "Distinct cohort SKUs with inventory or sales activity during this month.",
    "COUNT(DISTINCT active cohort SKUs)",
    "inventory",
  ],
  [
    "naSkuRate",
    "NA SKU %",
    "percent",
    "Share of the launched cohort that remains active in this month.",
    "Active cohort SKUs / Total SKUs launched in cohort × 100",
    "inventory",
  ],
  [
    "naSkuTotalRate",
    "NA SKU % (Total)",
    "percent",
    "Share of the store's active catalog represented by this cohort.",
    "Active cohort SKUs / Total active store SKUs × 100",
    "inventory",
  ],
  [
    "naInventory",
    "NA inventory",
    "inventory",
    "Cohort inventory units: ending units in launch month and starting units in later months.",
    "M0 ending inventory; later months starting inventory",
    "inventory",
  ],
  [
    "naInventoryRate",
    "NA Inventory %",
    "percent",
    "Share of total store inventory allocated to this cohort.",
    "Cohort inventory / Total store inventory × 100",
    "inventory",
  ],
  [
    "naSales",
    "NA sales",
    "currency",
    "Shopify Total Sales generated by products in this cohort during the month.",
    "SUM(cohort total_sales)",
    "sales",
  ],
  [
    "naSalesRate",
    "NA Sales %",
    "percent",
    "Share of Shopify Total Sales contributed by this cohort during the month.",
    "Cohort total_sales / Store total_sales × 100",
    "sales",
  ],
  [
    "landingSessions",
    "Landing sessions",
    "number",
    "Sessions where a product page belonging to this cohort was the customer's landing page.",
    "SUM(product landing-page sessions)",
    "traffic",
  ],
  [
    "orders",
    "Orders",
    "number",
    "Orders that included a product from this cohort during the month.",
    "COUNT(orders containing a cohort product)",
    "sales",
  ],
  [
    "conversionRate",
    "CR %",
    "percent",
    "Landing-session conversion rate for this cohort.",
    "Orders / Landing sessions × 100",
    "traffic",
  ],
];
const DETAIL_METRICS = [
  [
    "startingInventory",
    "Starting inventory",
    "number",
    "Product units available on the first day of the selected month or partial-month range.",
    "Inventory units at period start",
    "inventory",
  ],
  [
    "endingInventory",
    "Ending inventory",
    "number",
    "Product units available on the final day of the selected month or partial-month range.",
    "Inventory units at period end",
    "inventory",
  ],
  [
    "sales",
    "Sales",
    "currency",
    "Shopify Total Sales generated by this product during the month.",
    "SUM(product total_sales)",
    "sales",
  ],
  [
    "typeSalesRate",
    "Type sales %",
    "percent",
    "This product's share of sales within its product type.",
    "Product sales / Product-type sales × 100",
    "sales",
  ],
  [
    "totalSalesRate",
    "Total sales %",
    "percent",
    "This product's share of Shopify Total Sales during the month.",
    "Product total_sales / Store total_sales × 100",
    "sales",
  ],
  [
    "landingSessions",
    "Landing Sessions",
    "number",
    "Sessions where this product page was the customer's landing page.",
    "COUNT(sessions grouped by product landing page)",
    "traffic",
  ],
  [
    "orders",
    "Orders",
    "number",
    "Orders containing this product; one order counts once for the product.",
    "COUNT(DISTINCT orders containing product)",
    "sales",
  ],
  [
    "conversionRate",
    "CR %",
    "percent",
    "Percentage of product landing sessions that resulted in an order containing the product.",
    "Orders / Landing sessions × 100",
    "traffic",
  ],
];
function CustomMetricSelector({
  order,
  selected,
  onToggle,
  onMove,
  onSelectAll,
  onResetOrder,
}) {
  const [draggedKey, setDraggedKey] = useState("");
  const metricByKey = new Map(
    MATRIX_METRICS.map((metric) => [metric[0], metric]),
  );
  return (
    <details className="column-selector">
      <summary>
        <span className="column-selector-icon" aria-hidden="true">
          ▥
        </span>
        <span className="column-selector-title">Customise columns</span>
        <span className="column-selector-count">
          {selected.size}/{MATRIX_METRICS.length}
        </span>
        <span className="column-selector-chevron" aria-hidden="true">
          ⌄
        </span>
      </summary>
      <div className="column-selector-menu">
        <div className="column-selector-heading">
          <div>
            <strong>Customise columns</strong>
            <small>Choose what appears in the cohort matrix</small>
          </div>
        </div>
        <div className="column-selector-actions">
          <button type="button" onClick={onSelectAll}>
            Select all
          </button>
          <button type="button" onClick={onResetOrder}>
            Reset order
          </button>
        </div>
        <div className="column-selector-list">
          {order.map((key) => {
            const metric = metricByKey.get(key);
            if (!metric) return null;
            const checked = selected.has(key);
            return (
              <div
                className={`column-selector-row ${draggedKey === key ? "dragging" : ""}`}
                draggable
                key={key}
                onDragStart={() => setDraggedKey(key)}
                onDragEnd={() => setDraggedKey("")}
                onDragOver={(event) => event.preventDefault()}
                onDrop={() => {
                  if (draggedKey && draggedKey !== key) onMove(draggedKey, key);
                  setDraggedKey("");
                }}
              >
                <span className="drag-handle" aria-hidden="true">
                  ⠿
                </span>
                <label>
                  <input
                    type="checkbox"
                    checked={checked}
                    disabled={checked && selected.size === 1}
                    onChange={() => onToggle(key)}
                  />
                  <span>{metric[1]}</span>
                </label>
              </div>
            );
          })}
        </div>
        <div className="column-selector-footer">
          <span className="drag-handle" aria-hidden="true">
            ⠿
          </span>
          Drag rows to change the table order
        </div>
      </div>
    </details>
  );
}

function MetricTooltip({ name, definition, formula, tone = "inventory" }) {
  const [position, setPosition] = useState(null);
  const show = (event) => {
    const rect = event.currentTarget.getBoundingClientRect();
    const width = 290;
    setPosition({
      top: Math.min(rect.bottom + 8, window.innerHeight - 170),
      left: Math.max(
        12,
        Math.min(rect.left - 8, window.innerWidth - width - 12),
      ),
    });
  };
  return (
    <>
      <span
        className="metric-info-trigger"
        role="button"
        tabIndex="0"
        aria-label={`Explain ${name}`}
        onMouseEnter={show}
        onMouseLeave={() => setPosition(null)}
        onFocus={show}
        onBlur={() => setPosition(null)}
        onClick={(event) => event.stopPropagation()}
        onKeyDown={(event) => {
          if (event.key === "Enter" || event.key === " ") {
            event.preventDefault();
            event.stopPropagation();
            show(event);
          }
        }}
      >
        ⓘ
      </span>
      {position &&
        typeof document !== "undefined" &&
        createPortal(
          <div
            className="metric-tooltip"
            style={{ top: position.top, left: position.left }}
            role="tooltip"
          >
            <div className={`logic-badge ${tone}`}>{name}</div>
            <p>{definition}</p>
            <code>Formula: {formula}</code>
          </div>,
          document.body,
        )}
    </>
  );
}

function CohortLogicDrawer({ interval, classification }) {
  const [isOpen, setIsOpen] = useState(false);
  const periodName = interval === "week" ? "week" : "month";
  useEffect(() => {
    if (!isOpen) return undefined;
    const closeOnEscape = (event) => {
      if (event.key === "Escape") setIsOpen(false);
    };
    document.addEventListener("keydown", closeOnEscape);
    return () => document.removeEventListener("keydown", closeOnEscape);
  }, [isOpen]);

  const metric = (tone, name, definition, formula) => (
    <article className="logic-metric" key={name}>
      <div className={`logic-badge ${tone}`}>{name}</div>
      <p>{definition}</p>
      {formula && <code>Formula: {formula}</code>}
    </article>
  );

  return (
    <>
      <button
        type="button"
        className="logic-drawer-button"
        onClick={() => setIsOpen(true)}
      >
        📖 Calculation Logic &amp; Formulas
      </button>
      {isOpen &&
        typeof document !== "undefined" &&
        createPortal(
          <div
            className="logic-drawer-overlay"
            role="presentation"
            onMouseDown={(event) => {
              if (event.target === event.currentTarget) setIsOpen(false);
            }}
            onKeyDown={(event) => {
              if (event.key === "Escape") setIsOpen(false);
            }}
          >
            <aside
              className="logic-drawer"
              role="dialog"
              aria-modal="true"
              aria-labelledby="cohort-logic-title"
            >
              <header>
                <div>
                  <span>REPORT METHODOLOGY</span>
                  <h2 id="cohort-logic-title">
                    Calculation Logic &amp; Formulas
                  </h2>
                </div>
                <button
                  type="button"
                  aria-label="Close calculation logic"
                  onClick={() => setIsOpen(false)}
                >
                  ✕
                </button>
              </header>
              <div className="logic-drawer-content">
                <section>
                  <span className="logic-section-number">01</span>
                  <h3>The Core Mental Model</h3>
                  {metric(
                    "inventory",
                    `Launch ${periodName === "week" ? "Week" : "Month"}`,
                    `The earliest ${periodName} where a product showed active inventory or sales. Products active before the selected range are assigned to the first selected ${periodName}.`,
                    "startingInventory > 0 OR endingInventory > 0 OR totalSales > 0",
                  )}
                  {metric(
                    "traffic",
                    "Cohort Lifespan",
                    `Tracks performance across subsequent ${periodName}s to measure product decay, evergreen strength, and inventory absorption.`,
                  )}
                  {metric(
                    "traffic",
                    "Category Classification",
                    classification === "tag"
                      ? "Overall counts every product once. Tag breakdowns include a multi-tag product once in each tag it carries."
                      : "Products are grouped by their Shopify Product Type. Overall counts every product once.",
                  )}
                </section>
                <section>
                  <span className="logic-section-number">02</span>
                  <h3>Matrix Metrics Dictionary</h3>
                  {MATRIX_METRICS.slice(0, 8).map(
                    ([, name, , definition, formula, tone]) =>
                      metric(tone, name, definition, formula),
                  )}
                </section>
                <section>
                  <span className="logic-section-number">03</span>
                  <h3>Product Detail Table Metrics</h3>
                  {metric(
                    "inventory",
                    "Starting vs. Ending Inventory",
                    "Unit counts at day 1 versus the final day of the calendar month.",
                    "Period-start units compared with period-end units",
                  )}
                  {metric(
                    "inventory",
                    "Sell-Through %",
                    "The share of available units sold during the period.",
                    "Sales units / (Starting inventory + Restocks) × 100",
                  )}
                  {metric(
                    "traffic",
                    "Conversion Rate (CR %)",
                    "The share of landing sessions that produced an order containing the product.",
                    "Orders / Landing sessions × 100",
                  )}
                </section>
              </div>
            </aside>
          </div>,
          document.body,
        )}
    </>
  );
}

const dateString = (date) =>
  `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
const monthString = (date) => dateString(date).slice(0, 7);
function monthLabel(month) {
  const date = new Date(`${month}${month.length === 7 ? "-01" : ""}T00:00:00`);
  if (month.length === 10) {
    const end = new Date(date);
    end.setDate(end.getDate() + 6);
    const startLabel = date.toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
    });
    const endLabel = end.toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "2-digit",
    });
    return `${startLabel}–${endLabel}`;
  }
  return date
    .toLocaleDateString("en-US", { month: "short", year: "2-digit" })
    .replace(" ", "-");
}
function startOfWeek(value) {
  const date = new Date(`${value}T00:00:00`);
  const day = date.getDay();
  date.setDate(date.getDate() - (day === 0 ? 6 : day - 1));
  return dateString(date);
}
function weeksBetween(start, end) {
  const result = [];
  const cursor = new Date(`${startOfWeek(start)}T00:00:00`);
  const final = startOfWeek(end);
  while (dateString(cursor) <= final) {
    result.push(dateString(cursor));
    cursor.setDate(cursor.getDate() + 7);
  }
  return result;
}
function shiftMonth(month, offset) {
  const [year, value] = month.split("-").map(Number);
  return monthString(new Date(year, value - 1 + offset, 1));
}
function monthsBetween(start, end) {
  const result = [];
  for (let value = start; value <= end; value = shiftMonth(value, 1))
    result.push(value);
  return result;
}
function monthBounds(month, yesterday) {
  const [year, value] = month.split("-").map(Number);
  const naturalEnd = dateString(new Date(year, value, 0));
  return {
    start: `${month}-01`,
    end: naturalEnd > yesterday ? yesterday : naturalEnd,
  };
}
function weekBounds(week, yesterday) {
  const start = new Date(`${week}T00:00:00`);
  const endDate = new Date(start);
  endDate.setDate(endDate.getDate() + 6);
  const naturalEnd = dateString(endDate);
  return { start: week, end: naturalEnd > yesterday ? yesterday : naturalEnd };
}
const numericId = (value) => String(value ?? "").replace(/\D/g, "");
function numberFrom(row, key) {
  return Number(row?.[key]) || 0;
}

function normalizeRange(url, now = new Date()) {
  const yesterdayDate = new Date(
    now.getFullYear(),
    now.getMonth(),
    now.getDate() - 1,
  );
  const yesterday = dateString(yesterdayDate);
  const currentMonth = monthString(yesterdayDate);
  const earliestMonth = shiftMonth(currentMonth, -17);
  const earliest = `${earliestMonth}-01`;
  const classification =
    url.searchParams.get("classification") === "tag" ? "tag" : "type";
  const interval =
    url.searchParams.get("interval") === "week" ? "week" : "month";
  const currentWeekStart = new Date(`${startOfWeek(yesterday)}T00:00:00`);
  currentWeekStart.setDate(currentWeekStart.getDate() - 5 * 7);
  const defaultStart =
    interval === "week"
      ? dateString(currentWeekStart)
      : `${shiftMonth(currentMonth, -14)}-01`;
  const valid = (value) => /^\d{4}-\d{2}-\d{2}$/.test(value || "");
  let start = valid(url.searchParams.get("start"))
    ? url.searchParams.get("start")
    : defaultStart;
  let end = valid(url.searchParams.get("end"))
    ? url.searchParams.get("end")
    : yesterday;
  start = start < earliest ? earliest : start > yesterday ? yesterday : start;
  end = end > yesterday ? yesterday : end < earliest ? earliest : end;
  if (start > end) [start, end] = [end, start];
  return {
    start,
    end,
    startMonth: start.slice(0, 7),
    endMonth: end.slice(0, 7),
    earliest,
    earliestMonth,
    currentMonth,
    yesterday,
    classification,
    interval,
  };
}

async function mapConcurrent(items, limit, worker) {
  const output = new Array(items.length);
  let next = 0;
  async function consume() {
    while (next < items.length) {
      const index = next++;
      output[index] = await worker(items[index]);
    }
  }
  await Promise.all(
    Array.from({ length: Math.min(limit, items.length) }, consume),
  );
  return output;
}

async function fetchProductsByIds(admin, productIds) {
  const batches = [];
  for (let index = 0; index < productIds.length; index += 250)
    batches.push(productIds.slice(index, index + 250));
  const results = await mapConcurrent(batches, 2, async (batch) => {
    const response = await admin.graphql(
      `#graphql
      query NewArrivalMissingProducts($ids: [ID!]!) {
        nodes(ids: $ids) {
          ... on Product { id title productType tags handle featuredImage { url altText } }
        }
      }`,
      { variables: { ids: batch.map((id) => `gid://shopify/Product/${id}`) } },
    );
    const json = await response.json();
    return (json.data?.nodes || []).filter(Boolean);
  });
  return results.flat();
}

async function fetchPeriod(
  admin,
  shop,
  period,
  interval,
  yesterday,
  selectedStart,
  selectedEnd,
) {
  const bounds =
    interval === "week"
      ? weekBounds(period, yesterday)
      : monthBounds(period, yesterday);
  const start = bounds.start < selectedStart ? selectedStart : bounds.start;
  const end = bounds.end > selectedEnd ? selectedEnd : bounds.end;
  const cached = (dataset, query) =>
    runWithAnalyticsCache({
      shop,
      dataset: `new-arrival-${interval}-${dataset}-${period}`,
      rangeStart: start,
      rangeEnd: end,
      run: () => runShopifyQL(admin, query),
    });
  const [inventory, sales, storeSales, landingSessions] = await Promise.all([
    cached(
      "inventory-v2",
      `FROM inventory SHOW starting_inventory_units, ending_inventory_units GROUP BY product_id, product_title SINCE ${start} UNTIL ${end}`,
    ),
    cached(
      "product-sales-v2",
      `FROM sales SHOW total_sales, orders GROUP BY product_id, product_title SINCE ${start} UNTIL ${end}`,
    ),
    cached(
      "store-sales",
      `FROM sales SHOW total_sales SINCE ${start} UNTIL ${end}`,
    ),
    cached(
      "landing-sessions",
      `FROM sessions SHOW sessions WHERE landing_page_type = 'product' GROUP BY landing_page_path SINCE ${start} UNTIL ${end}`,
    ),
  ]);
  return { period, inventory, sales, storeSales, landingSessions };
}

function splitIntoChunks(values, size = 7) {
  const chunks = [];
  for (let index = 0; index < values.length; index += size)
    chunks.push(values.slice(index, index + size));
  return chunks;
}

function weekKey(value) {
  const match = String(value || "").match(/\d{4}-\d{2}-\d{2}/);
  return match ? startOfWeek(match[0]) : "";
}

function sliceWeeklyResult(result, period, chunkStart, chunkEnd) {
  return {
    ...result,
    chunkStart,
    chunkEnd,
    chunkRows: (result.rows || []).length,
    rows: (result.rows || []).filter((row) => weekKey(row.week) === period),
  };
}

async function fetchWeekChunk(
  admin,
  shop,
  periods,
  yesterday,
  selectedStart,
  selectedEnd,
) {
  const first = periods[0];
  const last = periods.at(-1);
  const start = first < selectedStart ? selectedStart : first;
  const naturalEnd = weekBounds(last, yesterday).end;
  const end = naturalEnd > selectedEnd ? selectedEnd : naturalEnd;
  const cached = (dataset, query) =>
    runWithAnalyticsCache({
      shop,
      dataset: `new-arrival-week-chunk-v1-${dataset}`,
      rangeStart: start,
      rangeEnd: end,
      run: () => runShopifyQL(admin, query),
    });
  const [inventory, sales, storeSales, landingSessions] = await Promise.all([
    cached(
      "inventory",
      `FROM inventory SHOW starting_inventory_units, ending_inventory_units GROUP BY week, product_id, product_title SINCE ${start} UNTIL ${end}`,
    ),
    cached(
      "product-sales",
      `FROM sales SHOW total_sales, orders GROUP BY week, product_id, product_title SINCE ${start} UNTIL ${end}`,
    ),
    cached(
      "store-sales",
      `FROM sales SHOW total_sales GROUP BY week SINCE ${start} UNTIL ${end}`,
    ),
    cached(
      "landing-sessions",
      `FROM sessions SHOW sessions WHERE landing_page_type = 'product' GROUP BY week, landing_page_path SINCE ${start} UNTIL ${end}`,
    ),
  ]);
  const datasets = [inventory, sales, storeSales, landingSessions];
  if (periods.length > 1 && datasets.some((result) => result.truncated)) {
    const middle = Math.ceil(periods.length / 2);
    const halves = [periods.slice(0, middle), periods.slice(middle)];
    const splitResults = [];
    for (const half of halves)
      splitResults.push(
        ...(await fetchWeekChunk(
          admin,
          shop,
          half,
          yesterday,
          selectedStart,
          selectedEnd,
        )),
      );
    return splitResults;
  }
  return periods.map((period) => ({
    period,
    inventory: sliceWeeklyResult(inventory, period, first, end),
    sales: sliceWeeklyResult(sales, period, first, end),
    storeSales: sliceWeeklyResult(storeSales, period, first, end),
    landingSessions: sliceWeeklyResult(landingSessions, period, first, end),
  }));
}

async function fetchWeeklyPeriods(admin, shop, periods, range) {
  const output = [];
  for (const chunk of splitIntoChunks(periods, 7))
    output.push(
      ...(await fetchWeekChunk(
        admin,
        shop,
        chunk,
        range.yesterday,
        range.start,
        range.end,
      )),
    );
  return output;
}

export const loader = async ({ request }) => {
  const { admin, session } = await authenticate.admin(request);
  const requestUrl = new URL(request.url);
  const range = normalizeRange(requestUrl);
  const categoryOnly = requestUrl.searchParams.get("categoryOnly") || "";
  const exportAll = requestUrl.searchParams.get("exportAll") === "1";
  const months =
    range.interval === "week"
      ? weeksBetween(range.start, range.end)
      : monthsBetween(range.startMonth, range.endMonth);
  const shopPromise = admin
    .graphql(
      `#graphql
    query NewArrivalShop {
      shop {
        currencyCode
        myshopifyDomain
        primaryDomain { url }
      }
    }`,
    )
    .then((response) => response.json())
    .then((json) => ({
      currency: json.data?.shop?.currencyCode || "USD",
      shopUrl: json.data?.shop?.primaryDomain?.url || "",
      storeHandle: String(json.data?.shop?.myshopifyDomain || "").replace(
        /\.myshopify\.com$/i,
        "",
      ),
    }));
  const analyticsPromise =
    range.interval === "week"
      ? fetchWeeklyPeriods(admin, session.shop, months, range)
      : mapConcurrent(months, 2, (period) =>
          fetchPeriod(
            admin,
            session.shop,
            period,
            range.interval,
            range.yesterday,
            range.start,
            range.end,
          ),
        );
  const [catalog, shopInfo, monthly] = await Promise.all([
    getProductCatalog(admin, session.shop),
    shopPromise,
    analyticsPromise,
  ]);
  const catalogById = new Map(
    catalog.products.map((product) => [numericId(product.id), product]),
  );
  const analyticsProductIds = new Set(
    monthly
      .flatMap((result) => [
        ...result.inventory.rows.map((row) => numericId(row.product_id)),
        ...result.sales.rows.map((row) => numericId(row.product_id)),
      ])
      .filter(Boolean),
  );
  const missingIds = [...analyticsProductIds].filter(
    (id) =>
      !catalogById.has(id) ||
      catalogById.get(id).featuredImage === undefined ||
      (range.classification === "tag" &&
        catalogById.get(id).tags === undefined),
  );
  if (missingIds.length) {
    const enrichedProducts = await fetchProductsByIds(admin, missingIds);
    for (const product of enrichedProducts)
      catalogById.set(numericId(product.id), product);
  }
  const productIdByHandle = new Map(
    [...catalogById]
      .map(([id, product]) => [product.handle, id])
      .filter(([handle]) => handle),
  );
  const sourceRows = [];
  const monthlyStoreSales = {};
  const warnings = [];
  const debug = [];
  for (const result of monthly) {
    const inventoryById = new Map(
      result.inventory.rows.map((row) => [numericId(row.product_id), row]),
    );
    const salesById = new Map(
      result.sales.rows.map((row) => [numericId(row.product_id), row]),
    );
    const sessionsById = new Map();
    for (const row of result.landingSessions.rows) {
      const match = String(row.landing_page_path || "").match(
        /\/products\/([^/?#]+)/,
      );
      if (!match) continue;
      let handle = match[1];
      try {
        handle = decodeURIComponent(handle);
      } catch {
        /* Keep Shopify's original handle if malformed. */
      }
      const productId = productIdByHandle.get(handle);
      if (productId)
        sessionsById.set(
          productId,
          (sessionsById.get(productId) || 0) + numberFrom(row, "sessions"),
        );
    }
    for (const productId of new Set([
      ...inventoryById.keys(),
      ...salesById.keys(),
      ...sessionsById.keys(),
    ])) {
      if (!productId) continue;
      const product = catalogById.get(productId) || {};
      const inventory = inventoryById.get(productId) || {};
      const sales = salesById.get(productId) || {};
      const storefrontUrl =
        product.handle && shopInfo.shopUrl
          ? `${shopInfo.shopUrl.replace(/\/$/, "")}/products/${product.handle}`
          : "";
      const adminUrl = shopInfo.storeHandle
        ? `https://admin.shopify.com/store/${shopInfo.storeHandle}/products/${productId}`
        : "";
      sourceRows.push({
        productId,
        period: result.period,
        title:
          product.title ||
          sales.product_title ||
          inventory.product_title ||
          `Product ${productId}`,
        productType: product.productType || "Others",
        productTags: product.tags || [],
        productUrl: storefrontUrl || adminUrl,
        handle: product.handle || "",
        imageUrl: product.featuredImage?.url || "",
        startingInventory: numberFrom(inventory, "starting_inventory_units"),
        endingInventory: numberFrom(inventory, "ending_inventory_units"),
        totalSales: numberFrom(sales, "total_sales"),
        orders: numberFrom(sales, "orders"),
        landingSessions: sessionsById.get(productId) || 0,
      });
    }
    monthlyStoreSales[result.period] = result.storeSales.rows.reduce(
      (sum, row) => sum + numberFrom(row, "total_sales"),
      0,
    );
    for (const [label, query] of [
      ["Inventory", result.inventory],
      ["Product sales", result.sales],
      ["Store sales", result.storeSales],
      ["Landing sessions", result.landingSessions],
    ]) {
      const showChunkStatus =
        !query.chunkStart || query.chunkStart === result.period;
      const periodLabel = query.chunkStart
        ? `${query.chunkStart} to ${query.chunkEnd}`
        : result.period;
      if (showChunkStatus && query.error)
        warnings.push(`${periodLabel} ${label}: ${query.error}`);
      if (showChunkStatus && query.truncated)
        warnings.push(
          `${periodLabel} ${label}: reached the 100,000-row limit.`,
        );
      if (showChunkStatus)
        debug.push({
          month: periodLabel,
          label,
          rows: query.chunkRows ?? query.rows.length,
          cache: query.cacheStatus || "live",
          attempts: query.attempts || 1,
          time: query.elapsedMs || 0,
        });
    }
  }
  const report = generateNewArrivalReport(
    sourceRows,
    months,
    monthlyStoreSales,
    range.classification,
    {
      categoryOnly,
      deferCategories: !categoryOnly && !exportAll,
    },
  );
  if (categoryOnly) return { category: report };
  return {
    report,
    currency: shopInfo.currency,
    range,
    warnings: [...new Set(warnings)],
    debug,
    catalogSource: catalog.source,
    catalogRefreshedAt: catalog.refreshedAt,
  };
};

function display(value, type, currency) {
  if (type === "percent") return `${((value || 0) * 100).toFixed(1)}%`;
  if (type === "currency")
    return new Intl.NumberFormat("en-IN", {
      style: "currency",
      currency,
      maximumFractionDigits: 0,
    }).format(value || 0);
  return new Intl.NumberFormat("en-IN", { maximumFractionDigits: 0 }).format(
    value || 0,
  );
}

function heatClass(key, value) {
  if (
    ![
      "naSalesRate",
      "naInventoryRate",
      "typeSalesRate",
      "totalSalesRate",
      "conversionRate",
    ].includes(key)
  )
    return "";
  if (value > 0.3) return "heat-high";
  if (value < 0.05) return "heat-low";
  return "heat-mid";
}

function MetricValue({ type, value, currency }) {
  if (type === "inventory" && Number(value) === 0)
    return <span className="oos-pill">0 · OOS</span>;
  return display(value, type, currency);
}

function LoadingState({ title = "Updating report", compact = false }) {
  return (
    <div className={`report-loading ${compact ? "compact" : ""}`} role="status">
      <span className="report-loading-spinner" aria-hidden="true" />
      <div>
        <strong>{title}</strong>
        <small>Please wait while the latest view is prepared.</small>
      </div>
    </div>
  );
}

function Matrix({
  title,
  matrix,
  months,
  currency,
  metrics,
  collapsible = false,
  density,
  classificationLabel,
  interval,
  initiallyExpanded = false,
}) {
  const [isExpanded, setIsExpanded] = useState(
    !collapsible || initiallyExpanded,
  );
  const table = (
    <div className="na-scroll matrix-scroll">
      <table className={`na-table matrix-table density-${density}`}>
        <thead>
          <tr>
            <th rowSpan="2" className="first cohort-head">
              Cohort
            </th>
            {months.map((month) => (
              <th className="month-group" key={month} colSpan={metrics.length}>
                <span>{monthLabel(month)}</span>
              </th>
            ))}
          </tr>
          <tr>
            {months.flatMap((month) =>
              metrics.map(([, label, , definition, formula, tone], index) => (
                <th
                  className={index === metrics.length - 1 ? "month-end" : ""}
                  key={`${month}-${label}`}
                >
                  <div className="metric-header-label">
                    <span>{label}</span>
                    <MetricTooltip
                      name={label}
                      definition={definition}
                      formula={formula}
                      tone={tone}
                    />
                  </div>
                </th>
              )),
            )}
          </tr>
        </thead>
        <tbody>
          <tr className="summary">
            <th className="first">Summary</th>
            {months.flatMap((month) =>
              metrics.map(([key, , type], index) => (
                <td
                  className={`${heatClass(key, matrix.grand[month]?.[key])} ${index === metrics.length - 1 ? "month-end" : ""}`}
                  key={`${month}-${key}`}
                >
                  <MetricValue
                    type={type}
                    value={matrix.grand[month]?.[key]}
                    currency={currency}
                  />
                </td>
              )),
            )}
          </tr>
          {matrix.rows.map((row, rowIndex) => (
            <tr
              className={rowIndex % 2 ? "row-odd" : "row-even"}
              key={row.cohort}
            >
              <th className="first">{row.label}</th>
              {months.flatMap((month) =>
                metrics.map(([key, , type], index) => (
                  <td
                    className={`${heatClass(key, row.values[month]?.[key])} ${index === metrics.length - 1 ? "month-end" : ""}`}
                    key={`${month}-${key}`}
                  >
                    {row.values[month] ? (
                      <MetricValue
                        type={type}
                        value={row.values[month][key]}
                        currency={currency}
                      />
                    ) : (
                      "—"
                    )}
                  </td>
                )),
              )}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
  return collapsible ? (
    <details
      className="na-card type-card"
      open={isExpanded}
      onToggle={(event) => setIsExpanded(event.currentTarget.open)}
    >
      <summary>
        <span>{title}</span>
        <small>{classificationLabel} cohort</small>
      </summary>
      {isExpanded && table}
    </details>
  ) : (
    <section className="na-card matrix-card">
      <div className="card-title">
        <div>
          <span>COHORT MATRIX</span>
          <h2>{title}</h2>
        </div>
        <small>
          {months.length} active {interval === "week" ? "weeks" : "months"}
        </small>
      </div>
      {table}
    </section>
  );
}

function LazyCategoryMatrix({
  title,
  loadUrl,
  months,
  currency,
  metrics,
  density,
  classificationLabel,
  interval,
}) {
  const fetcher = useFetcher();
  const requestedRef = useRef(false);
  const releaseRef = useRef(null);
  const cancelQueuedRef = useRef(null);
  const [wasOpened, setWasOpened] = useState(false);
  const matrix = fetcher.data?.category?.matrix;
  const request = useCallback(
    (priority = true) => {
      if (requestedRef.current) return;
      requestedRef.current = true;
      cancelQueuedRef.current = enqueueCategoryLoad((release) => {
        releaseRef.current = release;
        fetcher.load(loadUrl);
      }, priority);
    },
    [fetcher, loadUrl],
  );

  useEffect(() => {
    if (fetcher.state !== "idle" || !releaseRef.current) return;
    const release = releaseRef.current;
    releaseRef.current = null;
    release();
  }, [fetcher.state]);

  useEffect(
    () => () => {
      cancelQueuedRef.current?.();
      if (releaseRef.current) {
        const release = releaseRef.current;
        releaseRef.current = null;
        release();
      }
    },
    [],
  );

  if (matrix)
    return (
      <Matrix
        title={title}
        matrix={matrix}
        months={months}
        currency={currency}
        metrics={metrics}
        density={density}
        collapsible
        classificationLabel={classificationLabel}
        interval={interval}
        initiallyExpanded={wasOpened}
      />
    );

  return (
    <details
      className="na-card type-card pending-category"
      onToggle={(event) => {
        if (event.currentTarget.open) {
          setWasOpened(true);
          request();
        }
      }}
    >
      <summary>
        <span>{title}</span>
        <small>
          {fetcher.state === "loading"
            ? "Loading cohort…"
            : `${classificationLabel} cohort`}
        </small>
      </summary>
      <div className="category-loading-row">
        <span /> Preparing {title} cohort data…
      </div>
    </details>
  );
}

const csvCell = (value) => `"${String(value ?? "").replace(/"/g, '""')}"`;
const xmlEscape = (value) =>
  String(value ?? "").replace(
    /[<>&'"]/g,
    (char) =>
      ({
        "<": "&lt;",
        ">": "&gt;",
        "&": "&amp;",
        "'": "&apos;",
        '"': "&quot;",
      })[char],
  );

function downloadExport(content, format, filename) {
  const types = {
    csv: "text/csv;charset=utf-8",
    jsonl: "application/x-ndjson",
    xml: "application/xml",
  };
  const extension = format === "jsonl" ? "jsonl" : format;
  const prefix = format === "csv" ? "\uFEFF" : "";
  const url = URL.createObjectURL(
    new Blob([prefix, content], { type: types[format] }),
  );
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${filename}.${extension}`;
  anchor.click();
  URL.revokeObjectURL(url);
}

function detailExportRows(rows, months, currency) {
  return rows.map((row) => [
    row.title,
    row.productId,
    row.productType,
    `${monthLabel(row.cohort)} NA`,
    row.productUrl || "",
    ...months.flatMap((month) =>
      DETAIL_METRICS.map(([key, , type]) =>
        row.values[month]
          ? display(row.values[month][key], type, currency)
          : "—",
      ),
    ),
  ]);
}

function exportDetails(rows, months, currency, format) {
  const groupHeader = [
    "Product",
    "",
    "",
    "",
    "",
    ...months.flatMap((month) => [
      monthLabel(month),
      ...Array(DETAIL_METRICS.length - 1).fill(""),
    ]),
  ];
  const metricHeader = [
    "Product title",
    "Product ID",
    "Product type",
    "Launch cohort",
    "Product URL",
    ...months.flatMap(() => DETAIL_METRICS.map(([, label]) => label)),
  ];
  const dataRows = detailExportRows(rows, months, currency);
  let content;
  if (format === "csv") {
    content = [groupHeader, metricHeader, ...dataRows]
      .map((row) => row.map(csvCell).join(","))
      .join("\r\n");
  } else if (format === "jsonl") {
    content = [
      JSON.stringify({ recordType: "group_header", values: groupHeader }),
      JSON.stringify({ recordType: "metric_header", values: metricHeader }),
      ...dataRows.map((values) =>
        JSON.stringify({ recordType: "data", values }),
      ),
    ].join("\n");
  } else {
    const columns = metricHeader
      .map(
        (metric, index) =>
          `<column group="${xmlEscape(groupHeader[index])}" metric="${xmlEscape(metric)}"/>`,
      )
      .join("");
    content = `<report name="Cohort Details"><columns>${columns}</columns><rows>${dataRows
      .map(
        (row) =>
          `<row>${row.map((value) => `<cell>${xmlEscape(value)}</cell>`).join("")}</row>`,
      )
      .join("")}</rows></report>`;
  }
  downloadExport(content, format, "new-arrival-cohort-details");
}

function analysisSections(report) {
  return [
    { title: "Overall", matrix: report.overall },
    ...report.byProductType.map(({ type, matrix }) => ({
      title: type,
      matrix,
    })),
  ];
}

function exportAnalysis(sections, months, metrics, currency, format) {
  const exportedSections = sections
    .filter(({ matrix }) => matrix)
    .map(({ title, matrix }) => {
      const groupHeader = [
        "NA Cohort",
        ...months.flatMap((month) => [
          monthLabel(month),
          ...Array(metrics.length - 1).fill(""),
        ]),
      ];
      const metricHeader = [
        "NA Cohort",
        ...months.flatMap(() => metrics.map(([, label]) => label)),
      ];
      const valueCells = (values) =>
        months.flatMap((month) =>
          metrics.map(([key, , type]) =>
            values[month] ? display(values[month][key], type, currency) : "—",
          ),
        );
      const rows = [
        ["Summary", ...valueCells(matrix.grand)],
        ...matrix.rows.map((row) => [row.label, ...valueCells(row.values)]),
      ];
      return { title, groupHeader, metricHeader, rows };
    });
  let content;
  if (format === "csv") {
    content = exportedSections
      .flatMap((section, index) => [
        ...(index ? [[]] : []),
        [section.title],
        section.groupHeader,
        section.metricHeader,
        ...section.rows,
      ])
      .map((row) => row.map(csvCell).join(","))
      .join("\r\n");
  } else if (format === "jsonl") {
    content = exportedSections
      .flatMap((section) => [
        JSON.stringify({ recordType: "section", title: section.title }),
        JSON.stringify({
          recordType: "group_header",
          values: section.groupHeader,
        }),
        JSON.stringify({
          recordType: "metric_header",
          values: section.metricHeader,
        }),
        ...section.rows.map((values) =>
          JSON.stringify({ recordType: "data", values }),
        ),
      ])
      .join("\n");
  } else {
    content = `<report name="New Arrival Analysis">${exportedSections
      .map(
        (section) =>
          `<section name="${xmlEscape(section.title)}"><columns>${section.metricHeader
            .map(
              (metric, index) =>
                `<column group="${xmlEscape(section.groupHeader[index])}" metric="${xmlEscape(metric)}"/>`,
            )
            .join("")}</columns><rows>${section.rows
            .map(
              (row) =>
                `<row>${row.map((value) => `<cell>${xmlEscape(value)}</cell>`).join("")}</row>`,
            )
            .join("")}</rows></section>`,
      )
      .join("")}</report>`;
  }
  downloadExport(content, format, "new-arrival-analysis");
}

function Details({
  rows,
  months,
  currency,
  density,
  setDensity,
  classificationLabel,
  interval,
}) {
  const [page, setPage] = useState(1);
  const [query, setQuery] = useState("");
  const [typeFilter, setTypeFilter] = useState("all");
  const [stockFilter, setStockFilter] = useState("all");
  const [cohortFilter, setCohortFilter] = useState("all");
  const [isFiltering, setIsFiltering] = useState(false);
  const filterTimer = useRef(null);
  const [sort, setSort] = useState({ month: "", key: "", direction: "asc" });
  const latestMonth = months.at(-1);
  const markFilterUpdate = () => {
    window.clearTimeout(filterTimer.current);
    setIsFiltering(true);
    filterTimer.current = window.setTimeout(() => setIsFiltering(false), 220);
  };
  useEffect(() => () => window.clearTimeout(filterTimer.current), []);
  const types = useMemo(
    () => [...new Set(rows.map((row) => row.productType))].sort(),
    [rows],
  );
  const filteredRows = useMemo(
    () =>
      rows.filter((row) => {
        const search =
          `${row.title} ${row.handle} ${row.productId}`.toLowerCase();
        const ending = Number(row.values[latestMonth]?.endingInventory) || 0;
        const stock = ending === 0 ? "oos" : ending <= 5 ? "low" : "in";
        return (
          (!query || search.includes(query.toLowerCase())) &&
          (typeFilter === "all" || row.productType === typeFilter) &&
          (stockFilter === "all" || stock === stockFilter) &&
          (cohortFilter === "all" || row.cohort === cohortFilter)
        );
      }),
    [rows, query, typeFilter, stockFilter, cohortFilter, latestMonth],
  );
  const sortedRows = useMemo(() => {
    if (!sort.key) return filteredRows;
    return [...filteredRows].sort(
      (a, b) =>
        ((Number(a.values[sort.month]?.[sort.key]) || 0) -
          (Number(b.values[sort.month]?.[sort.key]) || 0)) *
          (sort.direction === "asc" ? 1 : -1) ||
        a.productId.localeCompare(b.productId),
    );
  }, [filteredRows, sort]);
  const toggleSort = (month, key) => {
    setSort((current) => ({
      month,
      key,
      direction:
        current.month === month &&
        current.key === key &&
        current.direction === "asc"
          ? "desc"
          : "asc",
    }));
    setPage(1);
  };
  const pages = Math.max(1, Math.ceil(sortedRows.length / PAGE_SIZE));
  const safePage = Math.min(page, pages);
  const visible = sortedRows.slice(
    (safePage - 1) * PAGE_SIZE,
    safePage * PAGE_SIZE,
  );
  return (
    <section className="na-card detail-card">
      <div className="detail-heading">
        <div>
          <span>PRODUCT-LEVEL VIEW</span>
          <h2>Cohort details</h2>
          <small>
            {filteredRows.length.toLocaleString()} of{" "}
            {rows.length.toLocaleString()} products
          </small>
        </div>
        <div className="detail-actions">
          <div className="density-toggle">
            <button
              className={density === "compact" ? "selected" : ""}
              onClick={() => setDensity("compact")}
            >
              Compact
            </button>
            <button
              className={density === "comfortable" ? "selected" : ""}
              onClick={() => setDensity("comfortable")}
            >
              Comfortable
            </button>
          </div>
          <details className="export-menu">
            <summary>⇩ Export</summary>
            <div>
              <button
                onClick={() =>
                  exportDetails(filteredRows, months, currency, "csv")
                }
              >
                CSV
              </button>
              <button
                onClick={() =>
                  exportDetails(filteredRows, months, currency, "jsonl")
                }
              >
                JSON Lines
              </button>
              <button
                onClick={() =>
                  exportDetails(filteredRows, months, currency, "xml")
                }
              >
                XML
              </button>
            </div>
          </details>
        </div>
      </div>
      <div className="filter-bar">
        <label className="search-box">
          <span>⌕</span>
          <input
            value={query}
            onChange={(event) => {
              markFilterUpdate();
              setQuery(event.target.value);
              setPage(1);
            }}
            placeholder="Search title, handle, or Product ID"
          />
        </label>
        <select
          value={typeFilter}
          onChange={(event) => {
            markFilterUpdate();
            setTypeFilter(event.target.value);
            setPage(1);
          }}
        >
          <option value="all">All {classificationLabel.toLowerCase()}s</option>
          {types.map((type) => (
            <option key={type}>{type}</option>
          ))}
        </select>
        <select
          value={stockFilter}
          onChange={(event) => {
            markFilterUpdate();
            setStockFilter(event.target.value);
            setPage(1);
          }}
        >
          <option value="all">All stock statuses</option>
          <option value="in">In stock</option>
          <option value="low">Low stock</option>
          <option value="oos">Out of stock</option>
        </select>
        <select
          value={cohortFilter}
          onChange={(event) => {
            markFilterUpdate();
            setCohortFilter(event.target.value);
            setPage(1);
          }}
        >
          <option value="all">
            All launch {interval === "week" ? "weeks" : "months"}
          </option>
          {months.map((month) => (
            <option key={month} value={month}>
              {monthLabel(month)} NA
            </option>
          ))}
        </select>
      </div>
      {isFiltering ? (
        <LoadingState title="Applying filters" compact />
      ) : (
        <>
          <div className="na-scroll detail-scroll">
            <table className={`na-table detail density-${density}`}>
              <thead>
                <tr>
                  <th rowSpan="2">Product</th>
                  <th rowSpan="2">{classificationLabel}</th>
                  <th rowSpan="2">Launch cohort</th>
                  {months.map((month) => (
                    <th
                      className="month-group"
                      key={month}
                      colSpan={DETAIL_METRICS.length}
                    >
                      <span>{monthLabel(month)}</span>
                    </th>
                  ))}
                </tr>
                <tr>
                  {months.flatMap((month) =>
                    DETAIL_METRICS.map(
                      ([key, label, , definition, formula, tone], index) => (
                        <th
                          className={
                            index === DETAIL_METRICS.length - 1
                              ? "month-end"
                              : ""
                          }
                          key={`${month}-${label}`}
                        >
                          <button
                            className="sort-button"
                            onClick={() => toggleSort(month, key)}
                          >
                            {label}
                            <span>
                              {sort.month === month && sort.key === key
                                ? sort.direction === "asc"
                                  ? "↑"
                                  : "↓"
                                : "↕"}
                            </span>
                            <MetricTooltip
                              name={label}
                              definition={definition}
                              formula={formula}
                              tone={tone}
                            />
                          </button>
                        </th>
                      ),
                    ),
                  )}
                </tr>
              </thead>
              <tbody>
                {visible.map((row, rowIndex) => (
                  <tr
                    className={rowIndex % 2 ? "row-odd" : "row-even"}
                    key={`${row.productId}-${row.productType}`}
                  >
                    <td>
                      <div className="product-cell">
                        {row.imageUrl ? (
                          <img src={row.imageUrl} alt="" />
                        ) : (
                          <span className="image-placeholder">◇</span>
                        )}
                        <div>
                          <a
                            href={row.productUrl || undefined}
                            target="_blank"
                            rel="noreferrer"
                            title={row.title}
                          >
                            {row.title}
                          </a>
                          <small>Product ID {row.productId}</small>
                        </div>
                      </div>
                    </td>
                    <td>
                      <span className="type-badge">{row.productType}</span>
                    </td>
                    <td>
                      <span className="cohort-badge">
                        {monthLabel(row.cohort)} NA
                      </span>
                    </td>
                    {months.flatMap((month) =>
                      DETAIL_METRICS.map(([key, , type], index) => (
                        <td
                          className={`${heatClass(key, row.values[month]?.[key])} ${index === DETAIL_METRICS.length - 1 ? "month-end" : ""}`}
                          key={`${month}-${key}`}
                        >
                          {row.values[month] ? (
                            key === "endingInventory" &&
                            Number(row.values[month][key]) === 0 ? (
                              <span className="oos-pill">0 · OOS</span>
                            ) : (
                              display(row.values[month][key], type, currency)
                            )
                          ) : (
                            "—"
                          )}
                        </td>
                      )),
                    )}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="pagination">
            <span>
              Showing{" "}
              {(safePage - 1) * PAGE_SIZE + (filteredRows.length ? 1 : 0)}–
              {Math.min(safePage * PAGE_SIZE, filteredRows.length)} of{" "}
              {filteredRows.length.toLocaleString()}
            </span>
            <div>
              <button
                disabled={safePage === 1}
                onClick={() => setPage(safePage - 1)}
              >
                Previous
              </button>
              <span>
                Page {safePage} of {pages}
              </span>
              <button
                disabled={safePage === pages}
                onClick={() => setPage(safePage + 1)}
              >
                Next
              </button>
            </div>
          </div>
        </>
      )}
    </section>
  );
}

export default function NewArrivalAnalysisPage() {
  const {
    report,
    currency,
    range,
    warnings,
    debug,
    catalogSource,
    catalogRefreshedAt,
  } = useLoaderData();
  const navigation = useNavigation();
  const isNavigating = navigation.state !== "idle";
  const [tab, setTab] = useState("analysis");
  const [density, setDensity] = useState("comfortable");
  const [isMetricUpdating, setIsMetricUpdating] = useState(false);
  const metricUpdateTimer = useRef(null);
  const defaultMetricOrder = MATRIX_METRICS.map(([key]) => key);
  const [metricOrder, setMetricOrder] = useState(defaultMetricOrder);
  const [selectedMetricKeys, setSelectedMetricKeys] = useState(
    () => new Set(defaultMetricOrder),
  );
  const analysisExportFetcher = useFetcher();
  const [pendingAnalysisExport, setPendingAnalysisExport] = useState("");
  const classificationLabel =
    range.classification === "tag" ? "Product tag" : "Product type";
  const metricByKey = new Map(
    MATRIX_METRICS.map((metric) => [metric[0], metric]),
  );
  const metrics = metricOrder
    .filter((key) => selectedMetricKeys.has(key))
    .map((key) => metricByKey.get(key));
  const runMetricUpdate = (update) => {
    window.clearTimeout(metricUpdateTimer.current);
    setIsMetricUpdating(true);
    metricUpdateTimer.current = window.setTimeout(() => {
      update();
      metricUpdateTimer.current = window.setTimeout(
        () => setIsMetricUpdating(false),
        120,
      );
    }, 60);
  };
  useEffect(() => () => window.clearTimeout(metricUpdateTimer.current), []);
  const toggleMetric = (key) =>
    runMetricUpdate(() =>
      setSelectedMetricKeys((current) => {
        const next = new Set(current);
        if (next.has(key)) {
          if (next.size === 1) return current;
          next.delete(key);
        } else next.add(key);
        return next;
      }),
    );
  const moveMetric = (source, target) =>
    runMetricUpdate(() =>
      setMetricOrder((current) => {
        const next = current.filter((key) => key !== source);
        next.splice(next.indexOf(target), 0, source);
        return next;
      }),
    );
  const selectAllMetrics = () =>
    runMetricUpdate(() => setSelectedMetricKeys(new Set(defaultMetricOrder)));
  const resetMetricOrder = () =>
    runMetricUpdate(() => setMetricOrder(defaultMetricOrder));
  const quickRanges =
    range.interval === "week"
      ? [
          [5, "Last 5 weeks"],
          [8, "Last 8 weeks"],
          [12, "Last 12 weeks"],
        ]
      : [
          [3, "Last 3 months"],
          [6, "Last 6 months"],
          [12, "Last 12 months"],
        ];
  const weeklyPresetStart = (count) => {
    const currentWeek = new Date(`${startOfWeek(range.yesterday)}T00:00:00`);
    currentWeek.setDate(currentWeek.getDate() - count * 7);
    return dateString(currentWeek);
  };
  const presetStart = (count) => {
    if (range.interval === "week") return weeklyPresetStart(count);
    const end = new Date(`${range.end}T00:00:00`);
    return dateString(
      new Date(end.getFullYear(), end.getMonth() - (count - 1), 1),
    );
  };
  const reportUrl = ({
    start = range.start,
    end = range.end,
    classification = range.classification,
    interval = range.interval,
  } = {}) =>
    `?start=${start}&end=${end}&classification=${classification}&interval=${interval}`;
  useEffect(() => {
    const exportedReport = analysisExportFetcher.data?.report;
    if (!pendingAnalysisExport || !exportedReport) return;
    exportAnalysis(
      analysisSections(exportedReport),
      exportedReport.months,
      metrics,
      currency,
      pendingAnalysisExport,
    );
    setPendingAnalysisExport("");
  }, [analysisExportFetcher.data, currency, metrics, pendingAnalysisExport]);
  const runAnalysisExport = (format) => {
    setPendingAnalysisExport(format);
    analysisExportFetcher.load(`${reportUrl()}&exportAll=1`);
  };
  const humanDate = (value) =>
    new Date(`${value}T00:00:00`).toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  return (
    <s-page heading="New Arrival Analysis">
      <div className="na-page">
        <section className="na-card control-card">
          <div className="control-main">
            <div className="control-label">
              <span>CUSTOM DATE RANGE</span>
              <strong>
                {humanDate(range.start)} – {humanDate(range.end)}
              </strong>
              <small>
                Available from {humanDate(range.earliest)} through yesterday
              </small>
            </div>
            <Form
              key={`${range.start}-${range.end}`}
              method="get"
              className="range-form"
            >
              <input
                type="hidden"
                name="classification"
                value={range.classification}
              />
              <input type="hidden" name="interval" value={range.interval} />
              <label>
                Start date
                <input
                  type="date"
                  name="start"
                  defaultValue={range.start}
                  min={range.earliest}
                  max={range.yesterday}
                />
              </label>
              <span>→</span>
              <label>
                End date
                <input
                  type="date"
                  name="end"
                  defaultValue={range.end}
                  min={range.earliest}
                  max={range.yesterday}
                />
              </label>
              <button type="submit">Apply</button>
            </Form>
            <CohortLogicDrawer
              interval={range.interval}
              classification={range.classification}
            />
          </div>
          <div className="quick-ranges">
            {quickRanges.map(([count, label]) => (
              <Link
                key={count}
                to={reportUrl({
                  start: presetStart(count),
                  end: range.interval === "week" ? range.yesterday : range.end,
                })}
              >
                {label}
              </Link>
            ))}
            {range.interval === "month" && (
              <Link to={reportUrl({ start: `${range.end.slice(0, 4)}-01-01` })}>
                Year-to-date
              </Link>
            )}
            <div className="report-segment-groups">
              <div className="report-segment">
                <span>Classify by</span>
                <Link
                  className={range.classification === "type" ? "selected" : ""}
                  to={reportUrl({ classification: "type" })}
                >
                  Product type
                </Link>
                <Link
                  className={range.classification === "tag" ? "selected" : ""}
                  to={reportUrl({ classification: "tag" })}
                >
                  Product tag
                </Link>
              </div>
              <div className="report-segment">
                <span>Group by</span>
                <Link
                  className={range.interval === "month" ? "selected" : ""}
                  to={reportUrl({ interval: "month" })}
                >
                  Month
                </Link>
                <Link
                  className={range.interval === "week" ? "selected" : ""}
                  to={reportUrl({
                    interval: "week",
                    start: weeklyPresetStart(5),
                    end: range.yesterday,
                  })}
                >
                  Week
                </Link>
              </div>
            </div>
          </div>
        </section>
        {isNavigating ? (
          <LoadingState title="Loading selected report" />
        ) : (
          <>
            {warnings.length > 0 && (
              <section className="warning">
                <strong>Some data may be incomplete:</strong>
                {warnings.map((warning) => (
                  <div key={warning}>{warning}</div>
                ))}
              </section>
            )}
            <details className="debug">
              <summary>View data freshness</summary>
              <p>
                Product catalog: {catalogSource} · refreshed{" "}
                {new Date(catalogRefreshedAt).toLocaleString()}
              </p>
              {debug.map((item) => (
                <div key={`${item.month}-${item.label}`}>
                  {item.month} · {item.label}: {item.rows} rows · {item.cache} ·{" "}
                  {item.attempts} attempt(s) · {item.time}ms
                </div>
              ))}
            </details>
            <div className="view-bar">
              <div className="tabs">
                <button
                  className={tab === "analysis" ? "active" : ""}
                  onClick={() => setTab("analysis")}
                >
                  New Arrival Analysis
                </button>
                <button
                  className={tab === "details" ? "active" : ""}
                  onClick={() => setTab("details")}
                >
                  Cohort Details
                </button>
              </div>
              {tab === "analysis" && (
                <div className="analysis-controls">
                  <CustomMetricSelector
                    order={metricOrder}
                    selected={selectedMetricKeys}
                    onToggle={toggleMetric}
                    onMove={moveMetric}
                    onSelectAll={selectAllMetrics}
                    onResetOrder={resetMetricOrder}
                  />
                  <details className="export-menu">
                    <summary>⇩ Export</summary>
                    <div>
                      {[
                        ["csv", "CSV"],
                        ["jsonl", "JSON Lines"],
                        ["xml", "XML"],
                      ].map(([format, label]) => (
                        <button
                          key={format}
                          disabled={
                            analysisExportFetcher.state === "loading" ||
                            analysisExportFetcher.state === "submitting"
                          }
                          onClick={() => runAnalysisExport(format)}
                        >
                          {pendingAnalysisExport === format
                            ? "Preparing…"
                            : label}
                        </button>
                      ))}
                    </div>
                  </details>
                </div>
              )}
            </div>
            {tab === "analysis" ? (
              isMetricUpdating ? (
                <LoadingState title="Updating visible columns" />
              ) : (
                <>
                  <Matrix
                    title="Overall"
                    matrix={report.overall}
                    months={report.months}
                    currency={currency}
                    metrics={metrics}
                    density={density}
                    classificationLabel={classificationLabel}
                    interval={range.interval}
                  />
                  {report.byProductType.map(({ type }) => (
                    <LazyCategoryMatrix
                      key={type}
                      title={type}
                      loadUrl={`${reportUrl()}&categoryOnly=${encodeURIComponent(type)}`}
                      months={report.months}
                      currency={currency}
                      metrics={metrics}
                      density={density}
                      classificationLabel={classificationLabel}
                      interval={range.interval}
                    />
                  ))}
                </>
              )
            ) : (
              <Details
                rows={report.details}
                months={report.months}
                currency={currency}
                density={density}
                setDensity={setDensity}
                classificationLabel={classificationLabel}
                interval={range.interval}
              />
            )}
          </>
        )}
      </div>
    </s-page>
  );
}

export const links = () => [{ rel: "stylesheet", href: styles }];
export const headers = (headersArgs) => boundary.headers(headersArgs);
