-- Audit Bot monthly analytics foundation.
-- Product text is stored once; monthly facts contain compact numeric values.

create table if not exists public.audit_stores (
  id bigint generated by default as identity primary key,
  shop_domain text not null unique,
  currency_code varchar(3) not null default 'USD',
  status text not null default 'active' check (status in ('active', 'uninstalled', 'paused')),
  installed_at timestamptz not null default now(),
  uninstalled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_products (
  id bigint generated by default as identity primary key,
  store_id bigint not null references public.audit_stores(id) on delete cascade,
  shopify_product_id bigint not null,
  title text not null default '',
  handle text not null default '',
  product_type text not null default '',
  status text not null default '',
  image_url text not null default '',
  shopify_created_at timestamptz,
  last_synced_at timestamptz not null default now(),
  unique (store_id, shopify_product_id)
);

create index if not exists audit_products_store_type_idx
  on public.audit_products (store_id, product_type);

create index if not exists audit_products_store_handle_idx
  on public.audit_products (store_id, handle);

create table if not exists public.audit_product_tags (
  product_id bigint not null references public.audit_products(id) on delete cascade,
  tag text not null,
  primary key (product_id, tag)
);

create index if not exists audit_product_tags_tag_idx
  on public.audit_product_tags (tag, product_id);

create table if not exists public.audit_product_month_metrics (
  store_id bigint not null references public.audit_stores(id) on delete cascade,
  product_id bigint not null references public.audit_products(id) on delete cascade,
  month date not null,
  first_day_in_inventory date,
  starting_inventory integer,
  ending_inventory integer,
  landing_sessions bigint not null default 0,
  orders bigint not null default 0,
  quantity_ordered bigint not null default 0,
  net_items_sold bigint not null default 0,
  reversed_quantity bigint not null default 0,
  gross_sales_minor bigint not null default 0,
  discounts_minor bigint not null default 0,
  sales_reversals_minor bigint not null default 0,
  net_sales_minor bigint not null default 0,
  shipping_charges_minor bigint not null default 0,
  return_fees_minor bigint not null default 0,
  taxes_minor bigint not null default 0,
  total_sales_minor bigint not null default 0,
  refreshed_at timestamptz not null default now(),
  primary key (store_id, product_id, month),
  check (month = date_trunc('month', month)::date)
);

create index if not exists audit_product_month_metrics_store_month_idx
  on public.audit_product_month_metrics (store_id, month);

create table if not exists public.audit_store_month_metrics (
  store_id bigint not null references public.audit_stores(id) on delete cascade,
  month date not null,
  active_products integer not null default 0,
  starting_inventory bigint,
  ending_inventory bigint,
  unique_orders bigint not null default 0,
  landing_sessions bigint not null default 0,
  total_sales_minor bigint not null default 0,
  refreshed_at timestamptz not null default now(),
  primary key (store_id, month),
  check (month = date_trunc('month', month)::date)
);

create table if not exists public.audit_sync_jobs (
  id bigint generated by default as identity primary key,
  store_id bigint references public.audit_stores(id) on delete cascade,
  job_type text not null,
  status text not null default 'pending' check (status in ('pending', 'running', 'completed', 'partial', 'failed')),
  range_start date,
  range_end date,
  attempts integer not null default 0,
  rows_written integer not null default 0,
  error_message text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz
);

create index if not exists audit_sync_jobs_store_created_idx
  on public.audit_sync_jobs (store_id, created_at desc);

-- Browser clients receive no table policies. Audit Bot writes through its
-- server-only service-role key, which bypasses RLS.
alter table public.audit_stores enable row level security;
alter table public.audit_products enable row level security;
alter table public.audit_product_tags enable row level security;
alter table public.audit_product_month_metrics enable row level security;
alter table public.audit_store_month_metrics enable row level security;
alter table public.audit_sync_jobs enable row level security;

revoke all on table public.audit_stores from anon, authenticated;
revoke all on table public.audit_products from anon, authenticated;
revoke all on table public.audit_product_tags from anon, authenticated;
revoke all on table public.audit_product_month_metrics from anon, authenticated;
revoke all on table public.audit_store_month_metrics from anon, authenticated;
revoke all on table public.audit_sync_jobs from anon, authenticated;

grant all on table public.audit_stores to service_role;
grant all on table public.audit_products to service_role;
grant all on table public.audit_product_tags to service_role;
grant all on table public.audit_product_month_metrics to service_role;
grant all on table public.audit_store_month_metrics to service_role;
grant all on table public.audit_sync_jobs to service_role;
grant usage, select on all sequences in schema public to service_role;
