-- Preserve product URL aliases over time so historical landing sessions remain
-- attributable after a Shopify product handle is renamed.

create table if not exists public.audit_product_handle_history (
  id bigint generated by default as identity primary key,
  store_id bigint not null references public.audit_stores(id) on delete cascade,
  product_id bigint not null references public.audit_products(id) on delete cascade,
  handle text not null,
  valid_from timestamptz not null,
  valid_to timestamptz,
  last_seen_at timestamptz not null default now(),
  constraint audit_product_handle_history_window_check
    check (valid_to is null or valid_to >= valid_from),
  constraint audit_product_handle_history_product_store_fk
    foreign key (product_id, store_id)
    references public.audit_products(id, store_id)
    on delete cascade,
  unique (product_id, handle, valid_from)
);

create unique index if not exists audit_product_handle_history_one_current_idx
  on public.audit_product_handle_history(product_id)
  where valid_to is null;
create index if not exists audit_product_handle_history_lookup_idx
  on public.audit_product_handle_history(store_id, handle, valid_from, valid_to);

insert into public.audit_product_handle_history(
  store_id, product_id, handle, valid_from, last_seen_at
)
select
  product.store_id,
  product.id,
  lower(trim(product.handle)),
  coalesce(product.shopify_created_at, product.last_seen_at, product.last_synced_at, now()),
  coalesce(product.last_seen_at, product.last_synced_at, now())
from public.audit_products product
where trim(coalesce(product.handle, '')) <> ''
  and not exists (
    select 1 from public.audit_product_handle_history history
    where history.product_id = product.id and history.valid_to is null
  );

create table if not exists public.audit_unmatched_landing_sessions (
  store_id bigint not null references public.audit_stores(id) on delete cascade,
  month date not null,
  handle text not null,
  sessions bigint not null default 0 check (sessions >= 0),
  refreshed_at timestamptz not null default now(),
  primary key (store_id, month, handle)
);

alter table public.audit_store_month_metrics
  add column if not exists matched_product_landing_sessions bigint not null default 0,
  add column if not exists unmatched_product_landing_sessions bigint not null default 0,
  add column if not exists store_sessions bigint not null default 0;

comment on table public.audit_product_handle_history is
  'Store-scoped history of Shopify product handles used to match historical landing URLs after product renames.';
comment on table public.audit_unmatched_landing_sessions is
  'Product landing sessions whose URL handle could not be matched to known current or historical product handles.';
comment on column public.audit_store_month_metrics.landing_sessions is
  'Backward-compatible matched product landing sessions used by existing reports.';
comment on column public.audit_store_month_metrics.matched_product_landing_sessions is
  'Product landing sessions matched to a product through current or historical handles.';
comment on column public.audit_store_month_metrics.unmatched_product_landing_sessions is
  'Product landing sessions whose handle could not be matched; excluded from product-level rows.';
comment on column public.audit_store_month_metrics.store_sessions is
  'Direct store-wide sessions returned by ShopifyQL; stored separately for reconciliation and not derived from products.';

create or replace view public.audit_product_handle_history_with_product
with (security_invoker = true)
as
select
  history.id,
  history.store_id,
  history.product_id,
  product.shopify_product_id,
  history.handle,
  history.valid_from,
  history.valid_to,
  history.last_seen_at
from public.audit_product_handle_history history
join public.audit_products product
  on product.id = history.product_id
 and product.store_id = history.store_id;

create or replace function public.reconcile_audit_product_handles(
  p_store_id bigint,
  p_handles jsonb,
  p_seen_at timestamptz
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  product_record record;
  current_record record;
  incoming_handle text;
  initial_valid_from timestamptz;
  changed integer := 0;
begin
  if p_store_id is null then raise exception 'store_id is required'; end if;
  if jsonb_typeof(coalesce(p_handles, 'null'::jsonb)) <> 'array' then
    raise exception 'handles must be a JSON array';
  end if;
  if p_seen_at is null then raise exception 'seen_at is required'; end if;

  for item in select value from jsonb_array_elements(p_handles)
  loop
    incoming_handle := lower(trim(coalesce(item->>'handle', '')));
    if incoming_handle = '' then continue; end if;

    select id, shopify_created_at into product_record
    from public.audit_products
    where store_id = p_store_id
      and shopify_product_id = (item->>'shopify_product_id')::bigint;
    if not found then
      raise exception 'product % does not belong to store_id %', item->>'shopify_product_id', p_store_id;
    end if;

    select id, handle into current_record
    from public.audit_product_handle_history
    where store_id = p_store_id
      and product_id = product_record.id
      and valid_to is null
    limit 1;

    if not found then
      initial_valid_from := coalesce(
        nullif(item->>'valid_from', '')::timestamptz,
        product_record.shopify_created_at,
        p_seen_at
      );
      insert into public.audit_product_handle_history(
        store_id, product_id, handle, valid_from, last_seen_at
      ) values (
        p_store_id, product_record.id, incoming_handle, initial_valid_from, p_seen_at
      );
      changed := changed + 1;
    elsif current_record.handle = incoming_handle then
      update public.audit_product_handle_history
      set last_seen_at = p_seen_at
      where id = current_record.id;
      changed := changed + 1;
    else
      update public.audit_product_handle_history
      set valid_to = p_seen_at, last_seen_at = p_seen_at
      where id = current_record.id;
      insert into public.audit_product_handle_history(
        store_id, product_id, handle, valid_from, last_seen_at
      ) values (
        p_store_id, product_record.id, incoming_handle, p_seen_at, p_seen_at
      );
      changed := changed + 2;
    end if;
  end loop;
  return changed;
end;
$$;

create or replace function public.replace_audit_store_month(
  p_store_id bigint,
  p_month date,
  p_product_metrics jsonb,
  p_store_metrics jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_product_count integer;
begin
  if p_store_id is null then raise exception 'store_id is required'; end if;
  if p_month is null then raise exception 'month is required'; end if;
  if jsonb_typeof(coalesce(p_product_metrics, 'null'::jsonb)) <> 'array' then raise exception 'product metrics must be a JSON array'; end if;
  if jsonb_typeof(coalesce(p_store_metrics, 'null'::jsonb)) <> 'object' then raise exception 'store metrics must be a JSON object'; end if;
  if not exists (select 1 from public.audit_stores where id = p_store_id) then raise exception 'unknown store_id %', p_store_id; end if;
  if exists (
    select 1 from jsonb_to_recordset(p_product_metrics) as metric(product_id bigint)
    left join public.audit_products product on product.id = metric.product_id and product.store_id = p_store_id
    where metric.product_id is null or product.id is null
  ) then raise exception 'one or more products do not belong to store_id %', p_store_id; end if;

  delete from public.audit_product_month_metrics where store_id = p_store_id and month = p_month;
  delete from public.audit_store_month_metrics where store_id = p_store_id and month = p_month;
  delete from public.audit_unmatched_landing_sessions where store_id = p_store_id and month = p_month;

  insert into public.audit_product_month_metrics (
    store_id, product_id, month, first_day_in_inventory, starting_inventory,
    ending_inventory, landing_sessions, product_orders, quantity_ordered,
    net_items_sold, reversed_quantity, gross_sales_minor, discounts_minor,
    sales_reversals_minor, net_sales_minor, shipping_charges_minor,
    return_fees_minor, taxes_minor, total_sales_minor, refreshed_at
  )
  select p_store_id, metric.product_id, p_month, metric.first_day_in_inventory,
    metric.starting_inventory, metric.ending_inventory, coalesce(metric.landing_sessions, 0),
    coalesce(metric.product_orders, metric.orders, 0), coalesce(metric.quantity_ordered, 0),
    coalesce(metric.net_items_sold, 0), coalesce(metric.reversed_quantity, 0),
    coalesce(metric.gross_sales_minor, 0), coalesce(metric.discounts_minor, 0),
    coalesce(metric.sales_reversals_minor, 0), coalesce(metric.net_sales_minor, 0),
    coalesce(metric.shipping_charges_minor, 0), coalesce(metric.return_fees_minor, 0),
    coalesce(metric.taxes_minor, 0), coalesce(metric.total_sales_minor, 0),
    coalesce(metric.refreshed_at, now())
  from jsonb_to_recordset(p_product_metrics) as metric(
    product_id bigint, first_day_in_inventory date, starting_inventory integer,
    ending_inventory integer, landing_sessions bigint, product_orders bigint,
    orders bigint, quantity_ordered bigint, net_items_sold bigint,
    reversed_quantity bigint, gross_sales_minor bigint, discounts_minor bigint,
    sales_reversals_minor bigint, net_sales_minor bigint,
    shipping_charges_minor bigint, return_fees_minor bigint, taxes_minor bigint,
    total_sales_minor bigint, refreshed_at timestamptz
  );
  get diagnostics v_product_count = row_count;

  insert into public.audit_store_month_metrics (
    store_id, month, active_products, starting_inventory, ending_inventory,
    unique_orders, landing_sessions, matched_product_landing_sessions,
    unmatched_product_landing_sessions, store_sessions, total_sales_minor, refreshed_at
  )
  select p_store_id, p_month, coalesce(metric.active_products, 0),
    greatest(coalesce(metric.starting_inventory, 0), 0),
    greatest(coalesce(metric.ending_inventory, 0), 0), coalesce(metric.unique_orders, 0),
    coalesce(metric.landing_sessions, 0), coalesce(metric.matched_product_landing_sessions, metric.landing_sessions, 0),
    coalesce(metric.unmatched_product_landing_sessions, 0), coalesce(metric.store_sessions, 0),
    coalesce(metric.total_sales_minor, 0), coalesce(metric.refreshed_at, now())
  from jsonb_to_record(p_store_metrics) as metric(
    active_products integer, starting_inventory bigint, ending_inventory bigint,
    unique_orders bigint, landing_sessions bigint, matched_product_landing_sessions bigint,
    unmatched_product_landing_sessions bigint, store_sessions bigint,
    total_sales_minor bigint, refreshed_at timestamptz
  );

  insert into public.audit_unmatched_landing_sessions(store_id, month, handle, sessions, refreshed_at)
  select p_store_id, p_month, lower(trim(item.handle)), coalesce(item.sessions, 0), now()
  from jsonb_to_recordset(coalesce(p_store_metrics->'unmatched_landing_pages', '[]'::jsonb))
    as item(handle text, sessions bigint)
  where trim(coalesce(item.handle, '')) <> '' and coalesce(item.sessions, 0) > 0;

  return v_product_count + 1;
end;
$$;

revoke all on table public.audit_product_handle_history from public, anon, authenticated;
revoke all on table public.audit_unmatched_landing_sessions from public, anon, authenticated;
revoke all on table public.audit_product_handle_history_with_product from public, anon, authenticated;
grant select, insert, update, delete on table public.audit_product_handle_history to service_role;
grant select, insert, update, delete on table public.audit_unmatched_landing_sessions to service_role;
grant select on table public.audit_product_handle_history_with_product to service_role;
revoke all on function public.reconcile_audit_product_handles(bigint, jsonb, timestamptz) from public, anon, authenticated;
grant execute on function public.reconcile_audit_product_handles(bigint, jsonb, timestamptz) to service_role;

